import { Artwork } from './types';

export const PRINTMAKING_ARTWORKS: Artwork[] = [
  {
    "id": "1",
    "number": "01",
    "titleZh": "",
    "titleEn": "",
    "author": "basin",
    "descriptionZh": "",
    "descriptionEn": "",
    "themeZh": "刻出你与世界的流动",
    "themeEn": "Carve the 'flow' between you and the world",
    "session": "S2",
    "themeColor": "#EF4444",
    "themeTextColor": "#FFFFFF"
  },
  {
    "id": "2",
    "number": "02",
    "titleZh": "Our Pain",
    "titleEn": "Our Pain",
    "author": "Sunny",
    "descriptionZh": "",
    "descriptionEn": "",
    "themeZh": "刻出你与世界的流动",
    "themeEn": "Carve the 'flow' between you and the world",
    "session": "S2",
    "themeColor": "#EF4444",
    "themeTextColor": "#FFFFFF"
  },
  {
    "id": "3",
    "number": "03",
    "titleZh": "",
    "titleEn": "",
    "author": "leyi",
    "descriptionZh": "",
    "descriptionEn": "",
    "themeZh": "刻出你与世界的流动",
    "themeEn": "Carve the 'flow' between you and the world",
    "session": "S2",
    "themeColor": "#EF4444",
    "themeTextColor": "#FFFFFF"
  },
  {
    "id": "4",
    "number": "04",
    "titleZh": "",
    "titleEn": "",
    "author": "Yidi",
    "descriptionZh": "",
    "descriptionEn": "",
    "themeZh": "刻出你与世界的流动",
    "themeEn": "Carve the 'flow' between you and the world",
    "session": "S2",
    "themeColor": "#EF4444",
    "themeTextColor": "#FFFFFF"
  },
  {
    "id": "5",
    "number": "05",
    "titleZh": "",
    "titleEn": "",
    "author": "Siqi",
    "descriptionZh": "",
    "descriptionEn": "",
    "themeZh": "刻出你与世界的流动",
    "themeEn": "Carve the 'flow' between you and the world",
    "session": "S2",
    "themeColor": "#EF4444",
    "themeTextColor": "#FFFFFF"
  },
  {
    "id": "6",
    "number": "06",
    "titleZh": "",
    "titleEn": "",
    "author": "Lesley",
    "descriptionZh": "",
    "descriptionEn": "",
    "themeZh": "刻出你与世界的流动",
    "themeEn": "Carve the 'flow' between you and the world",
    "session": "S2",
    "themeColor": "#EF4444",
    "themeTextColor": "#FFFFFF"
  },
  {
    "id": "7",
    "number": "07",
    "titleZh": "",
    "titleEn": "",
    "author": "Tenya",
    "descriptionZh": "",
    "descriptionEn": "",
    "themeZh": "刻出你与世界的流动",
    "themeEn": "Carve the 'flow' between you and the world",
    "session": "S2",
    "themeColor": "#EF4444",
    "themeTextColor": "#FFFFFF"
  },
  {
    "id": "8",
    "number": "08",
    "titleZh": "兰花",
    "titleEn": "Orchid",
    "author": "",
    "descriptionZh": "隐喻女性的阴蒂，表达了对生殖器切割(female genital cutting)的抗议，希望女性都能对自身的器官更accept并fight for it。",
    "descriptionEn": "Using the orchid as a metaphor for the clitoris, this work protests female genital cutting (FGC), encouraging women to accept their bodies and fight for their bodily autonomy.",
    "themeZh": "消除性别暴力16日行动",
    "themeEn": "16 Days of Activism Against GBV",
    "session": "S3",
    "themeColor": "#F97316",
    "themeTextColor": "#FFFFFF"
  },
  {
    "id": "9",
    "number": "09",
    "titleZh": "无孩爱猫女炮轰性别暴力",
    "titleEn": "Childless Cat Ladies Blast GBV",
    "author": "H.Y.Y",
    "descriptionZh": "通过猫(无孩爱猫女象征)对阵狗(美国梦及传统家庭男性幻想象征)，表达了对于现实困境进行反抗和开战的姿态。",
    "descriptionEn": "Using a cat (symbol of the 'childless cat lady') facing off against a dog (symbol of the 'American Dream' and traditional patriarchal domesticity), this piece adopts a defiant stance against systemic struggles.",
    "themeZh": "消除性别暴力16日行动",
    "themeEn": "16 Days of Activism Against GBV",
    "session": "S3",
    "themeColor": "#F97316",
    "themeTextColor": "#FFFFFF"
  },
  {
    "id": "10",
    "number": "10",
    "titleZh": "不要对性别暴力视而不见",
    "titleEn": "Don't Turn a Blind Eye to GBV",
    "author": "yue",
    "descriptionZh": "画了流血流泪的双眼，批判社会对性别暴力(如家暴、性侵)的忽视，呼吁大家勇敢团结起来对抗。",
    "descriptionEn": "Featuring eyes shedding blood and tears, this work critiques societal indifference toward domestic violence and sexual assault, calling for courageous solidarity.",
    "themeZh": "消除性别暴力16日行动",
    "themeEn": "16 Days of Activism Against GBV",
    "session": "S3",
    "themeColor": "#F97316",
    "themeTextColor": "#FFFFFF"
  },
  {
    "id": "11",
    "number": "11",
    "titleZh": "Anti Violence 握拳",
    "titleEn": "Anti Violence: The Fist",
    "author": "Haiyin",
    "descriptionZh": "描绘不同美甲/形状/残缺的手指挣脱镣铐，代表酷儿群体团结起来对抗性别暴力。",
    "descriptionEn": "Depicting hands with diverse nails, shapes, and imperfections breaking free from shackles, this represents the queer community uniting against violence.",
    "themeZh": "消除性别暴力16日行动",
    "themeEn": "16 Days of Activism Against GBV",
    "session": "S3",
    "themeColor": "#F97316",
    "themeTextColor": "#FFFFFF"
  },
  {
    "id": "12",
    "number": "12",
    "titleZh": "Belay in You",
    "titleEn": "Belay in You",
    "author": "",
    "descriptionZh": "用攀岩的制动和保护装置Guigui及Belayship概念，希望社群中的问责机制能够建立在保护、信任和伙伴合作之上。",
    "descriptionEn": "Utilizing the concept of 'Belayship' and climbing safety devices (Grigri), this piece advocates for community accountability mechanisms built on protection, trust, and partnership.",
    "themeZh": "消除性别暴力16日行动",
    "themeEn": "16 Days of Activism Against GBV",
    "session": "S3",
    "themeColor": "#F97316",
    "themeTextColor": "#FFFFFF"
  },
  {
    "id": "13",
    "number": "13",
    "titleZh": "Soup",
    "titleEn": "Soup",
    "author": "小树",
    "descriptionZh": "将汤碗、隔热手套等家务元素与嘴唇结合，象征女性刻板印象和性别暴力的现状。",
    "descriptionEn": "By blending domestic elements like soup bowls and oven mitts with lips, this work symbolizes the current state of gender stereotypes and domestic GBV.",
    "themeZh": "消除性别暴力16日行动",
    "themeEn": "16 Days of Activism Against GBV",
    "session": "S3",
    "themeColor": "#F97316",
    "themeTextColor": "#FFFFFF"
  },
  {
    "id": "14",
    "number": "14",
    "titleZh": "STOP IMAGE ABUSE",
    "titleEn": "STOP IMAGE ABUSE",
    "author": "",
    "descriptionZh": "表达了未经许可散播照片对当事人造成的伤害。",
    "descriptionEn": "Expresses the profound harm caused to individuals by the non-consensual distribution of private images.",
    "themeZh": "消除性别暴力16日行动",
    "themeEn": "16 Days of Activism Against GBV",
    "session": "S3",
    "themeColor": "#F97316",
    "themeTextColor": "#FFFFFF"
  },
  {
    "id": "15",
    "number": "15",
    "titleZh": "别忘记她",
    "titleEn": "Don't Forget Her",
    "author": "Lesley",
    "descriptionZh": "灵感来源于那个被铁链和暴力困在大山中的铁链女，希望我们都能够铭记她。",
    "descriptionEn": "Inspired by the 'Xuzhou Eight-Child Mother' (the woman in chains) who was trapped by violence in the mountains; it is a plea for us to never let her memory fade.",
    "themeZh": "消除性别暴力16日行动",
    "themeEn": "16 Days of Activism Against GBV",
    "session": "S3",
    "themeColor": "#F97316",
    "themeTextColor": "#FFFFFF"
  },
  {
    "id": "16",
    "number": "16",
    "titleZh": "Speak Up!",
    "titleEn": "Speak Up!",
    "author": "Sunny",
    "descriptionZh": "以标语和图形结合Speak Up与Stand Up，强调了打破沉默、站起来是消除性别暴力的第一步。",
    "descriptionEn": "Combining slogans with graphics, this piece merges 'Speak Up' and 'Stand Up,' emphasizing that breaking the silence and taking a stand are the first steps toward ending violence.",
    "themeZh": "消除性别暴力16日行动",
    "themeEn": "16 Days of Activism Against GBV",
    "session": "S3",
    "themeColor": "#F97316",
    "themeTextColor": "#FFFFFF"
  },
  {
    "id": "17",
    "number": "17",
    "titleZh": "Name it!",
    "titleEn": "Name it!",
    "author": "ly",
    "descriptionZh": "表达了消除性别暴力的第一步就是命名它。它不是家丑，不是你太敏感了。它是性别暴力，是施暴者。请认真、严肃地对待!",
    "descriptionEn": "Asserts that the first step to ending violence is naming it. It is not a 'private family matter,' nor is it 'being too sensitive.' It is gender-based violence; they are perpetrators.",
    "themeZh": "消除性别暴力16日行动",
    "themeEn": "16 Days of Activism Against GBV",
    "session": "S3",
    "themeColor": "#F97316",
    "themeTextColor": "#FFFFFF"
  },
  {
    "id": "18",
    "number": "18",
    "titleZh": "Queer Here",
    "titleEn": "Queer Here",
    "author": "",
    "descriptionZh": "受到活动海报和酷儿到的启发，结合活动现场的fika，创造出自己想要的春节。",
    "descriptionEn": "Inspired by the event poster and the phrase 'Queer Arrival,' this piece incorporates the workshop's 'fika' (coffee break) to envision a self-defined Lunar New Year.",
    "themeZh": "酷儿春节",
    "themeEn": "Queer Spring Festival",
    "session": "S4",
    "themeColor": "#FFB208",
    "themeTextColor": "#4D26B2"
  },
  {
    "id": "19",
    "number": "19",
    "titleZh": "马踏飞机(平安有钱有工作有成果版)",
    "titleEn": "Horse Stepping on a Plane",
    "author": "",
    "descriptionZh": "用马踏飞燕的原型，加入了自己贪心的愿望，希望可以自由地去往世界上任何地方；无论怎么过年，都希望获得从自己心意出发的幸福。",
    "descriptionEn": "Based on the 'Galloping Horse Treading on a Swallow' motif, this piece adds 'greedy' personal wishes: the freedom to travel anywhere and the pursuit of a happiness that stems purely from one's own heart.",
    "themeZh": "酷儿春节",
    "themeEn": "Queer Spring Festival",
    "session": "S4",
    "themeColor": "#FFB208",
    "themeTextColor": "#4D26B2"
  },
  {
    "id": "20",
    "number": "20",
    "titleZh": "2026大滑特滑",
    "titleEn": "2026: Sliding Through",
    "author": "Zoe",
    "descriptionZh": "2026可以大滑特滑，过年的仪式却很少大说特说，原来家家户户都过的春节也是一种私人的体验。",
    "descriptionEn": "In 2026, one can 'slide' freely into the future, yet the rituals of the New Year are rarely discussed in depth. This work reveals that even a holiday celebrated by every household is a deeply personal experience.",
    "themeZh": "酷儿春节",
    "themeEn": "Queer Spring Festival",
    "session": "S4",
    "themeColor": "#FFB208",
    "themeTextColor": "#4D26B2"
  },
  {
    "id": "21",
    "number": "21",
    "titleZh": "灶神奶奶",
    "titleEn": "The Kitchen Grandmother",
    "author": "",
    "descriptionZh": "在最初的记载里，灶神是女性，她主管人间饮食、督查人间一切事物；但在民间灶神图里，男性形象灶王爷逐渐成为主导，原本的灶神也被边缘化。作品塑造了阔面、威严的女性灶神形象，希望可以在春节传统里夺回女性的权力和叙事。",
    "descriptionEn": "Historically, the Kitchen Deity was female, overseeing all human affairs. However, folk tradition eventually centered the male 'Kitchen King,' marginalizing the original goddess. This work portrays a majestic female Kitchen Deity, seeking to reclaim female power and narrative within tradition.",
    "themeZh": "酷儿春节",
    "themeEn": "Queer Spring Festival",
    "session": "S4",
    "themeColor": "#FFB208",
    "themeTextColor": "#4D26B2"
  },
  {
    "id": "22",
    "number": "22",
    "titleZh": "猫到福到",
    "titleEn": "When Cats Arrive, Blessings Arrive",
    "author": "",
    "descriptionZh": "表现了对于春节记忆的反思，也用福字的正方形寄托了无孩渴猫女朴素的春节愿望，猫就是福。",
    "descriptionEn": "A reflection on New Year memories that uses the traditional square Fu format to express a simple wish for 'childless cat ladies': that cats are the true source of blessing.",
    "themeZh": "酷儿春节",
    "themeEn": "Queer Spring Festival",
    "session": "S4",
    "themeColor": "#FFB208",
    "themeTextColor": "#4D26B2"
  },
  {
    "id": "23",
    "number": "23",
    "titleZh": "全家福",
    "titleEn": "The Family Portrait",
    "author": "",
    "descriptionZh": "讲述了一个故事: 因为疫情，我两年没有回国，再回国时已是物是人非；出国前一起吃年夜饭时拍的照片，居然成了最后一张快乐的全家福。",
    "descriptionEn": "A story of loss and change: 'Due to the pandemic, I couldn't return home for two years. When I finally did, everything was different. The photo we took at our last New Year's Eve dinner before I went abroad turned out to be our final happy family portrait.'",
    "themeZh": "酷儿春节",
    "themeEn": "Queer Spring Festival",
    "session": "S4",
    "themeColor": "#FFB208",
    "themeTextColor": "#4D26B2"
  },
  {
    "id": "24",
    "number": "24",
    "titleZh": "万马奔腾",
    "titleEn": "A Gallop of Ten Thousand Horses",
    "author": "",
    "descriptionZh": "绘制了各种各样的马: 杀马特、牛马、会爬树的马、旋转木马……希望新的一年各种各样的人都可以马到成功。",
    "descriptionEn": "Featuring a diverse herd: the subcultural Shamate, the 'Ox-Horse' (exploited laborers), tree-climbing horses, and carousels. It carries the wish that in the new year, people of all kinds will achieve their own version of success.",
    "themeZh": "酷儿春节",
    "themeEn": "Queer Spring Festival",
    "session": "S4",
    "themeColor": "#FFB208",
    "themeTextColor": "#4D26B2"
  },
  {
    "id": "25",
    "number": "25",
    "titleZh": "Let's 發春",
    "titleEn": "Let's Bloom",
    "author": "泽泽",
    "descriptionZh": "描绘了圆桌之上多只手举杯相碰的瞬间，这些形形色色的手代表着形形色色的酷儿群体；春节在画面中是充满饭席与酒桌的团圆时刻。",
    "descriptionEn": "Depicting diverse hands clinking glasses around a circular table, this piece represents the spectrum of the queer community. It reclaims the New Year banquet as a moment of queer reunion and vitality.",
    "themeZh": "酷儿春节",
    "themeEn": "Queer Spring Festival",
    "session": "S4",
    "themeColor": "#FFB208",
    "themeTextColor": "#4D26B2"
  },
  {
    "id": "26",
    "number": "26",
    "titleZh": "Queer福",
    "titleEn": "Queer Fu",
    "author": "",
    "descriptionZh": "重组了春节的概念，把传统的福字变得活泼起来。如今，人们对幸福的理解已不再只是礼和田，因此也加入了?、!和Queer。",
    "descriptionEn": "Reimagining the concept of Fu (blessing), this piece breathes playfulness into the traditional character. Symbols like '?', '!', and 'Queer' are woven into its structure.",
    "themeZh": "酷儿春节",
    "themeEn": "Queer Spring Festival",
    "session": "S4",
    "themeColor": "#FFB208",
    "themeTextColor": "#4D26B2"
  },
  {
    "id": "27",
    "number": "27",
    "titleZh": "元宝奶",
    "titleEn": "Nipple Ingot",
    "author": "ly",
    "descriptionZh": "在春节语境中，元宝是几乎无人质疑的吉祥物。作品将元宝替换为奶头这一通常被视为私密甚至不登大雅之堂的身体符号。通过这种置换，作品试图打破春节话语中关于成功、规范与祝福对象的单一想象。",
    "descriptionEn": "In the New Year context, the gold ingot (Yuanbao) is a universal symbol of secular success. By replacing the ingot with the nipple -- a bodily symbol often deemed 'indecent' -- the work challenges the narrow imagination of success.",
    "themeZh": "酷儿春节",
    "themeEn": "Queer Spring Festival",
    "session": "S4",
    "themeColor": "#FFB208",
    "themeTextColor": "#4D26B2"
  },
  {
    "id": "28",
    "number": "28",
    "titleZh": "妈到成功",
    "titleEn": "Ma (Mother) to Success",
    "author": "Lesley",
    "descriptionZh": "呈现的一副对联——莫妈不停蹄汗妈功劳，祝信妈由缰放妈南山——寄托了对于女性长辈不被春节的劳动所束缚的祝愿。今年正好是马年，便在马字旁边加了一个女字。",
    "descriptionEn": "Featuring a couplet that plays on the words 'Horse' (Ma) and 'Mother' (Ma), this work hopes to liberate female elders from the domestic labor of the holiday. By adding the 'woman' radical to the character for horse, the artist wishes for everyone to find joy and their true selves.",
    "themeZh": "酷儿春节",
    "themeEn": "Queer Spring Festival",
    "session": "S4",
    "themeColor": "#FFB208",
    "themeTextColor": "#4D26B2"
  },
  {
    "id": "29",
    "number": "29",
    "titleZh": "朋友",
    "titleEn": "Friends / Harmony",
    "author": "Awlyn",
    "descriptionZh": "作品使用了蓝色和红色这对互补色，代表着强烈且不同的个性，但在碰撞中亦能创造平衡。在瑞典与中国关系趋于紧张、战争恐惧蔓延的背景下，作品试图传达: 恐惧不应成为常态，跨越国境的人们依然可以作为朋友共处。",
    "descriptionEn": "This piece uses the complementary colors of blue and red, representing strong and distinct personalities that find balance through collision. The work suggests that fear should not be the norm, and that people across borders can still exist as friends.",
    "themeZh": "我们与战争的距离",
    "themeEn": "Between Us and War",
    "session": "S6",
    "themeColor": "#22C55E",
    "themeTextColor": "#FFFFFF"
  },
  {
    "id": "30",
    "number": "30",
    "titleZh": "Star Peace",
    "titleEn": "Star Peace",
    "author": "",
    "descriptionZh": "作品灵感来自《太空百合战姬》，想象人类社会能够发展到在银河星际中和谐自由地生活，没有资源和权力的争斗，只有宇宙中永恒的宁静。",
    "descriptionEn": "Inspired by 'Space Lesbian Princess,' this work envisions a human society that has evolved to live harmoniously and freely in the galaxy, free from struggles over resources and power.",
    "themeZh": "我们与战争的距离",
    "themeEn": "Between Us and War",
    "session": "S6",
    "themeColor": "#22C55E",
    "themeTextColor": "#FFFFFF"
  },
  {
    "id": "31",
    "number": "31",
    "titleZh": "共创世界",
    "titleEn": "Co-creating the World",
    "author": "Lesley",
    "descriptionZh": "作品围绕和平鸽展开，通过保留并整合工作坊中每一位参与者的测试版痕迹与创作元素，表达了对世界共荣与和平的集体祈愿。",
    "descriptionEn": "Centered around the dove of peace, this piece integrates the traces and elements from every participant's test plate, expressing a collective aspiration for global prosperity and peace.",
    "themeZh": "我们与战争的距离",
    "themeEn": "Between Us and War",
    "session": "S6",
    "themeColor": "#22C55E",
    "themeTextColor": "#FFFFFF"
  },
  {
    "id": "32",
    "number": "32",
    "titleZh": "飞跃苦海",
    "titleEn": "Leaping Over the Sea of Bitterness",
    "author": "",
    "descriptionZh": "作品灵感源于Critical Gallery的艺术创作，通过飞鱼的意象表达了一种希望，祈愿身处苦难中的人们能够拥有飞越困境的生命力与自由。",
    "descriptionEn": "Inspired by the art of Critical Gallery, this work uses the imagery of 'flying fish' to express hope, wishing that those in suffering find the vitality and freedom to leap over their hardships.",
    "themeZh": "我们与战争的距离",
    "themeEn": "Between Us and War",
    "session": "S6",
    "themeColor": "#22C55E",
    "themeTextColor": "#FFFFFF"
  },
  {
    "id": "33",
    "number": "33",
    "titleZh": "格尔朋卡",
    "titleEn": "Guerponca",
    "author": "大盆",
    "descriptionZh": "作品灵感源于《格尔尼卡》，通过解构手法将自然生态、动植物与人类，同战火中的拉扯、碰撞与毁灭感交织在一起，呈现出对战争深层的解构与反思。",
    "descriptionEn": "Inspired by Guernica, this work employs deconstructive techniques to interweave nature, animals, and humanity with the tension, collision, and sense of ruin found in the flames of war.",
    "themeZh": "我们与战争的距离",
    "themeEn": "Between Us and War",
    "session": "S6",
    "themeColor": "#22C55E",
    "themeTextColor": "#FFFFFF"
  },
  {
    "id": "34",
    "number": "34",
    "titleZh": "AN ACTION HAVE CONSEQUENCE",
    "titleEn": "AN ACTION HAVE CONSEQUENCE",
    "author": "yueyue",
    "descriptionZh": "作品描绘了一个因自身行为而遭到报应的人物，旨在探讨在暴力传播中个体行为的连带责任，并以此提醒人们在行动前必须审视其可能带来的后果。",
    "descriptionEn": "Depicting a figure facing retribution for their actions, this piece explores the individual's accountability in the spread of violence.",
    "themeZh": "我们与战争的距离",
    "themeEn": "Between Us and War",
    "session": "S6",
    "themeColor": "#22C55E",
    "themeTextColor": "#FFFFFF"
  },
  {
    "id": "35",
    "number": "35",
    "titleZh": "IF ANTS RULE THE WORLD",
    "titleEn": "IF ANTS RULE THE WORLD",
    "author": "星",
    "descriptionZh": "作品将画面中的人换成了蚂蚁，试图想象一个并非由人类主导的世界，或讨论中提到的建酷儿国的想法。",
    "descriptionEn": "By replacing humans with ants, this work imagines a world not dominated by humanity, or the idea of 'Building a Queer Nation' mentioned in discussion.",
    "themeZh": "我们与战争的距离",
    "themeEn": "Between Us and War",
    "session": "S6",
    "themeColor": "#22C55E",
    "themeTextColor": "#FFFFFF"
  },
  {
    "id": "36",
    "number": "36",
    "titleZh": "战火",
    "titleEn": "Flames of War",
    "author": "Bao",
    "descriptionZh": "作品表达了在杀戮与离散的讯息不断涌现的当下，个体虽然感到无力，但仍试图通过创作向身处战火中的人们传递一份最素朴的牵挂。",
    "descriptionEn": "This work expresses the feeling of individual powerlessness amidst constant news of slaughter and separation, yet seeks to convey a simple, profound sense of concern for those caught in the crossfire.",
    "themeZh": "我们与战争的距离",
    "themeEn": "Between Us and War",
    "session": "S6",
    "themeColor": "#22C55E",
    "themeTextColor": "#FFFFFF"
  },
  {
    "id": "37",
    "number": "37",
    "titleZh": "Dance, not war",
    "titleEn": "Dance, not war",
    "author": "Ren",
    "descriptionZh": "作品将Rave文化的反抗与和平精神融入版画，通过音乐无国界、爱能消解身份标签的视角，表达了以舞蹈代替战争的美好愿景。",
    "descriptionEn": "Merging the spirit of resistance and peace from Rave culture into printmaking, this work envisions a world where music transcends borders and love dissolves identity labels.",
    "themeZh": "我们与战争的距离",
    "themeEn": "Between Us and War",
    "session": "S6",
    "themeColor": "#22C55E",
    "themeTextColor": "#FFFFFF"
  },
  {
    "id": "38",
    "number": "38",
    "titleZh": "Machine OR Not",
    "titleEn": "Machine OR Not",
    "author": "鹅老师",
    "descriptionZh": "",
    "descriptionEn": "",
    "themeZh": "玫瑰与面包",
    "themeEn": "Roses and Bread",
    "session": "S7",
    "themeColor": "#3B82F6",
    "themeTextColor": "#FFFFFF"
  },
  {
    "id": "39",
    "number": "39",
    "titleZh": "世界由我建造",
    "titleEn": "The world is built by me",
    "author": "猛子",
    "descriptionZh": "",
    "descriptionEn": "",
    "themeZh": "玫瑰与面包",
    "themeEn": "Roses and Bread",
    "session": "S7",
    "themeColor": "#3B82F6",
    "themeTextColor": "#FFFFFF"
  },
  {
    "id": "40",
    "number": "40",
    "titleZh": "不想上班",
    "titleEn": "I don't want to work",
    "author": "Shuo Miao",
    "descriptionZh": "写作时我所处的角落，有我的猫，有顺畅的网络和一台电脑，有绿植和咖啡。",
    "descriptionEn": "In the corner where I write, there's my cat, a smooth internet connection, a computer, some green plants, and a cup of coffee.",
    "themeZh": "玫瑰与面包",
    "themeEn": "Roses and Bread",
    "session": "S7",
    "themeColor": "#3B82F6",
    "themeTextColor": "#FFFFFF"
  },
  {
    "id": "41",
    "number": "41",
    "titleZh": "Just a bathroom, Take your time",
    "titleEn": "Just a bathroom, Take your time",
    "author": "Tantan",
    "descriptionZh": "日常生活总是和屎尿屁相关，我们总说带薪拉屎，但我们真的有足够舒适的卫生间吗? 足够的女厕? 足够的非二元卫生间?",
    "descriptionEn": "Daily life is always tied up with 'piss, shit, and farts.' We always joke about getting paid to poop, but do we actually have restrooms that are comfortable enough? Enough women's toilets? Enough all-gender restrooms?",
    "themeZh": "玫瑰与面包",
    "themeEn": "Roses and Bread",
    "session": "S7",
    "themeColor": "#3B82F6",
    "themeTextColor": "#FFFFFF"
  },
  {
    "id": "42",
    "number": "42",
    "titleZh": "口苗口王又见",
    "titleEn": "MIAO-WANG GUAN (The Temple of Meows and Woofs)",
    "author": "Jiashu",
    "descriptionZh": "我们可以像曾经的修女和道士，利用规则和主动性团结在一起，创造一个理想化的工作空间，做我们真正心之所向的工作，被可爱的人和猫猫狗狗围绕，在舒适的氛围里创造劳动。",
    "descriptionEn": "Just like the nuns and Taoist monks of the past, we can leverage structures and collective agency to unite, carving out an idealized workspace of our own.",
    "themeZh": "玫瑰与面包",
    "themeEn": "Roses and Bread",
    "session": "S8",
    "themeColor": "#4D26B2",
    "themeTextColor": "#FFB208"
  },
  {
    "id": "43",
    "number": "43",
    "titleZh": "歧视终结者",
    "titleEn": "Discrimination Terminator",
    "author": "Yue Yue",
    "descriptionZh": "因为在Brainstorm的过程中聊到了基因编辑，让歧视的人生病，还有机器人替我们工作的IDEA，所以设计了一个歧视终结者。",
    "descriptionEn": "During our brainstorming session, the ideas went wild -- from gene editing to robots taking over our daily toil. That's how the 'Discrimination Terminator' was born.",
    "themeZh": "玫瑰与面包",
    "themeEn": "Roses and Bread",
    "session": "S8",
    "themeColor": "#4D26B2",
    "themeTextColor": "#FFB208"
  },
  {
    "id": "44",
    "number": "44",
    "titleZh": "PICKING PEBBLES",
    "titleEn": "PICKING PEBBLES",
    "author": "AMANDARDEA",
    "descriptionZh": "我把它看作一个重新想象工作的空间: 既可以盘点当下和过去的困境，也可以朝向未来。我们需要在现实中播种之前，先集体梦想出替代方案。",
    "descriptionEn": "I saw it as a space to reimagine work; allowing for both an inventory of current and past struggles as well as orient toward the future. We need to collectively dream up alternatives before we can sow the seeds in reality.",
    "themeZh": "玫瑰与面包",
    "themeEn": "Roses and Bread",
    "session": "S8",
    "themeColor": "#4D26B2",
    "themeTextColor": "#FFB208"
  },
  {
    "id": "45",
    "number": "45",
    "titleZh": "新贝蒂不是小丑",
    "titleEn": "The New Betty is no joker",
    "author": "hyy",
    "descriptionZh": "工作中总是有许多苦闷，作为女性获得面包更加困难，但终有一天我们都会获得满意的工作。贝蒂小姐如此有能力，做过飞行员、歌手、护士。希望新时代的贝蒂小姐可以穿舒适的衣服发挥自己的价值。",
    "descriptionEn": "Work is often filled with endless frustration, and earning a living as a woman is even harder. Miss Betty is so incredibly capable -- having worked as a pilot, a singer, and a nurse. I hope that the modern-day Miss Bettys can wear what makes them comfortable and fully realize their worth.",
    "themeZh": "玫瑰与面包",
    "themeEn": "Roses and Bread",
    "session": "S8",
    "themeColor": "#4D26B2",
    "themeTextColor": "#FFB208"
  },
  {
    "id": "46",
    "number": "46",
    "titleZh": "Hope in Work",
    "titleEn": "Hope in Work",
    "author": "阿兰 Alan",
    "descriptionZh": "少数群体在绝大多数工作环境里都需要装直。通过这个活动，大家终于有了一个说出口的机会，能彻底放松下来! 这也表达了对工作的期许: 环境变得更好，钱也挣到。",
    "descriptionEn": "In the vast majority of work environments, minorities constantly have to 'act straight.' This project finally gives everyone a chance to just spit it out and let their guard down -- it feels great! A wish for the future of work: a much better environment, and getting paid what we're worth.",
    "themeZh": "玫瑰与面包",
    "themeEn": "Roses and Bread",
    "session": "S8",
    "themeColor": "#4D26B2",
    "themeTextColor": "#FFB208"
  },
  {
    "id": "47",
    "number": "47",
    "titleZh": "简历",
    "titleEn": "The Resume",
    "author": "Judy",
    "descriptionZh": "在很多男性主导的领域中，女性在职场常常遭遇不公平对待、隐性甚至公开的歧视。曾经在求职时被建议不要在简历中加入照片，因为很多公司更倾向录用男性。希望在未来，简历是否包含照片应当是个人选择。",
    "descriptionEn": "In many male-dominated fields, women frequently encounter unfair treatment and biases. When applying for jobs, I was once advised to leave my photo off my resume, because many companies favored male applicants. I hope that in the future, including a photo on a resume becomes a purely personal choice.",
    "themeZh": "玫瑰与面包",
    "themeEn": "Roses and Bread",
    "session": "S8",
    "themeColor": "#4D26B2",
    "themeTextColor": "#FFB208"
  },
  {
    "id": "48",
    "number": "48",
    "titleZh": "Love yourself as a flower",
    "titleEn": "Love yourself as a flower",
    "author": "Stars",
    "descriptionZh": "我们需要一定的空间来保护自己，有些空间留给自己休息、整理思绪、充满能量，才能更好地生活、学习、工作。我们每个人都是一颗星，无数闪耀的星才能组成一个宇宙。",
    "descriptionEn": "We need a personal sanctuary to protect ourselves -- a quiet space to rest, gather our thoughts, and recharge. Each of us is a star, and only when countless shining stars align can we form a universe.",
    "themeZh": "玫瑰与面包",
    "themeEn": "Roses and Bread",
    "session": "S8",
    "themeColor": "#4D26B2",
    "themeTextColor": "#FFB208"
  },
  {
    "id": "49",
    "number": "49",
    "titleZh": "众手成墙",
    "titleEn": "Hands build a wall",
    "author": "查无此人",
    "descriptionZh": "群体力量对个体的围困或保护",
    "descriptionEn": "Riot is the siege or the protection that collective power imposes upon the individual.",
    "themeZh": "反叛青年",
    "themeEn": "Riot Me",
    "session": "S9",
    "themeColor": "#EC4899",
    "themeTextColor": "#FFFFFF"
  },
  {
    "id": "50",
    "number": "50",
    "titleZh": "存在",
    "titleEn": "Exist",
    "author": "Amy",
    "descriptionZh": "天大地大中的一棵树，以及树旁的脚印。\n可以坦然地、无畏地、独立地停驻。\n也可以坦然地、无畏地、独立地行走",
    "descriptionEn": "Riot is a single tree in the vastness of the universe, and the footprints left beside it.\nOne can stand still—composed, fearless, and independent.\nOne can also forge ahead—composed, fearless, and independent.",
    "themeZh": "反叛青年",
    "themeEn": "Riot Me",
    "session": "S9",
    "themeColor": "#EC4899",
    "themeTextColor": "#FFFFFF"
  },
  {
    "id": "51",
    "number": "51",
    "titleZh": "Throw the first brick",
    "titleEn": "Throw the first brick",
    "author": "Tantan",
    "descriptionZh": "Throw the first brick是指代Stonewall Riot运动的短语。反抗的勇气、念头，迈出的第一步就像这破墙的砖，即使没办法立刻摧毁禁锢你的囚牢，但已产生了希望的裂缝，终有一天你会获得自由。",
    "descriptionEn": "\"Throw the first brick\" is a phrase synonymous with the Stonewall Riots. The courage to resist, the spark of defianace, and the very first step you take are just like that brick hurled to break the wall. Even if it cannot instantly shatter the prison that confines you, it has already cracked it open with hope. One day, you will be free.",
    "themeZh": "反叛青年",
    "themeEn": "Riot Me",
    "session": "S9",
    "themeColor": "#EC4899",
    "themeTextColor": "#FFFFFF"
  },
  {
    "id": "52",
    "number": "52",
    "titleZh": "Ctrl Z",
    "titleEn": "Ctrl Z",
    "author": "Momo",
    "descriptionZh": "冲破世俗刻板印象/桎梏\n不用走别人给你设定的道路",
    "descriptionEn": "Shatter societal stereotypes and shackles.\nYou never have to walk the path others have paved for you.",
    "themeZh": "反叛青年",
    "themeEn": "Riot Me",
    "session": "S9",
    "themeColor": "#EC4899",
    "themeTextColor": "#FFFFFF"
  }
];
